export const SEARCH_MOVIE_TYPE = "SEARCH_MOVIE";
export const RESET_MOVIE_TYPE = "RESET_MOVIE";
export const ADD_MOVIE_TYPE = "ADD_MOVIE";
export const DELETE_SELECTED_MOVIE_TYPE = "DELETE_SELECTED_MOVIE";
